name: Backend CICD

# Trigger Condition
on:
  push:
    branches: 
      - backend-main
  pull_request:
    types: [ closed ]
    branches: 
      - backend-main

# tasks
jobs:
  build_and_deploy:
    name: build_and_deploy
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # gcloud auth
    - name: Set up gcloud Auth - backend database
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_DB_CREDENTIALS }}

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 363.0.0'

    - name: 'Enable API'
      run: |
        gcloud services enable sqladmin.googleapis.com
      
    # create environment
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./backend/requirements.txt

    - name: Create .env file
      # You may pin to the exact commit or the version.
      # uses: SpicyPizza/create-envfile@ace6d4f5d7802b600276c23ca417e669f1a06f6f
      uses: SpicyPizza/create-envfile@v2.0.3
      with:
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        envkey_JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

        # Database setting
        envkey_INSTANCE_NAME: "loyal-curve-418602:asia-east1:sdm-g4-db"
        envkey_DB_NAME: "tripbuddy"
        envkey_DB_USER: "root"
        envkey_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        envkey_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}

        # Mail Server
        envkey_MAIL_SERVER: "smtp.gmail.com"
        envkey_MAIL_PORT: 587
        envkey_MAIL_USE_TLS: True
        envkey_MAIL_DEFAULT_SENDER: ("admin", "tripbuddy4sdm@gmail.com")
        envkey_MAIL_USERNAME: "tripbuddy4sdm@gmail.com"
        envkey_MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

        # gemini setting
        envkey_APP_ENGINE_PROJECT_ID: "planar-effect-420508"
        envkey_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

        # Google Login setting
        envkey_GOOGLE_OAUTH2_CLIENT_ID: "688645866898-1mdotjk1gn8on9kf74b7gudinurcarui.apps.googleusercontent.com"
        envkey_PROJECT_ID: "loyal-curve-418602"
        envkey_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        envkey_REDIRECT_URIS: ${{ vars.REDIRECT_URIS }}

    # run test
    - name: Run Tests
      run: |
        cd backend
        pytest

    # gcloud auth
    - name: 'Set up gcloud Auth - backend service'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCP_APP_CREDENTIALS }}

    # deploy to cloud run
    - name: Deploy to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'tripbuddy'
        source: 'backend'
        region: 'asia-east1'
